# Generated by Django 2.1.12 on 2019-10-09 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20191006_1506'),
        ('App', '0002_userprofile_role'),
    ]

    operations = [
    ]
