# Generated by Django 2.1.12 on 2019-10-26 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0002_auto_20191006_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_fifth', models.CharField(blank=True, max_length=1000, null=True)),
                ('password_fourth', models.CharField(blank=True, max_length=1000, null=True)),
                ('password_third', models.CharField(blank=True, max_length=1000, null=True)),
                ('password_second', models.CharField(blank=True, max_length=1000, null=True)),
                ('password_first', models.CharField(blank=True, max_length=1000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pervious Passwords',
            },
        ),
    ]
