# Generated by Django 2.1.12 on 2019-10-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_previouspassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='failure_login_attempts',
            new_name='failed_login_attemts',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_suspended',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_suspended',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
