# Generated by Django 2.1.12 on 2019-10-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20191026_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_suspended',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
