# Generated by Django 2.1.12 on 2019-10-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20191026_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_suspended',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
