# Generated by Django 2.1.12 on 2019-10-26 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20191026_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='failed_login_attemts',
            new_name='failed_login_attempts',
        ),
    ]
