# Generated by Django 2.1.12 on 2019-10-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20191026_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='forgot_password_hash',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
