# Generated by Django 2.1.12 on 2019-10-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_userprofile_forgot_password_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='OrgName',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
