# Generated by Django 2.1.12 on 2019-10-27 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20191027_0734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='previouspassword',
            old_name='password_fifth',
            new_name='fifth_password',
        ),
        migrations.RenameField(
            model_name='previouspassword',
            old_name='password_first',
            new_name='first_password',
        ),
        migrations.RenameField(
            model_name='previouspassword',
            old_name='password_fourth',
            new_name='fourth_password',
        ),
        migrations.RenameField(
            model_name='previouspassword',
            old_name='password_second',
            new_name='second_password',
        ),
        migrations.RenameField(
            model_name='previouspassword',
            old_name='password_third',
            new_name='third_password',
        ),
    ]
