# Generated by Django 2.1.12 on 2019-10-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20191027_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='previouspassword',
            name='fifth_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='previouspassword',
            name='first_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='previouspassword',
            name='fourth_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='previouspassword',
            name='second_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='previouspassword',
            name='third_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
