# Generated by Django 2.1.12 on 2019-10-27 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_auto_20191027_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='previouspassword',
            old_name='fifth_password',
            new_name='f_password',
        ),
        migrations.RenameField(
            model_name='previouspassword',
            old_name='first_password',
            new_name='fi_password',
        ),
        migrations.RenameField(
            model_name='previouspassword',
            old_name='fourth_password',
            new_name='fo_password',
        ),
        migrations.RenameField(
            model_name='previouspassword',
            old_name='second_password',
            new_name='s_password',
        ),
        migrations.RenameField(
            model_name='previouspassword',
            old_name='third_password',
            new_name='t_password',
        ),
    ]
