# Generated by Django 2.1.12 on 2019-10-27 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_auto_20191027_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresethistory',
            name='login_time',
        ),
        migrations.RemoveField(
            model_name='passwordresethistory',
            name='password',
        ),
        migrations.RemoveField(
            model_name='passwordresethistory',
            name='user',
        ),
    ]
