# Generated by Django 2.1.12 on 2019-10-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_auto_20191027_0950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresethistory',
            options={'verbose_name_plural': 'Password Reset History'},
        ),
        migrations.AddField(
            model_name='passwordresethistory',
            name='fifth_last_user_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='passwordresethistory',
            name='fourth_last_user_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='passwordresethistory',
            name='last_user_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='passwordresethistory',
            name='second_last_user_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='passwordresethistory',
            name='third_last_user_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
